import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router';
import { useApp, Tenant } from '../../context/AppContext';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Textarea } from '../../components/ui/textarea';
import { Badge } from '../../components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../../components/ui/card';
import {
  ArrowLeft, Check, CheckCircle2, ShieldCheck,
  Search, Lock, MapPin, Mail, Phone, Building2, UserCheck, RefreshCw
} from 'lucide-react';
import { toast } from 'sonner';
import { partnerAPI, Partner } from '../../api/client';
import { convertKoreanToQwerty } from '../../utils/koreanConverter';
import { openDaumPostcode } from '../../utils/daumPostcode';

const RELIGION_TYPES = [
  { key: 'buddhist',   label: '불교 (사찰 · 암자)',       badge: '사찰 전용', defaultDesc: '부처님의 자비와 지혜로 평화와 행복을 찾는 도량입니다.' },
  { key: 'protestant', label: '기독교 (교회)',           badge: '교회 전용', defaultDesc: '은혜와 나눔이 넘치는 따뜻한 믿음의 공동체입니다.' },
  { key: 'catholic',   label: '천주교 (성당)',           badge: '성당 전용', defaultDesc: '사랑과 나눔이 함께하는 따뜻한 신앙 공동체입니다.' },
  { key: 'charity',    label: '구호 · 사회복지재단',      badge: 'NPO 재단',  defaultDesc: '소외된 이웃에게 희망과 온정을 전하는 복지 재단입니다.' },
  { key: 'general',    label: '비영리 공익법인 · 기타',   badge: '공익법인',  defaultDesc: '공익과 사회적 가치를 실현하는 비영리 사단법인입니다.' },
] as const;

const BANKS = [
  '국민은행', '신한은행', '우리은행', '하나은행', 'NH농협', '기업은행',
  '카카오뱅크', '토스뱅크', 'SC제일은행', '우체국', '수협', '새마을금고', '신협'
];

export default function SystemAdminTenantCreate() {
  const navigate = useNavigate();
  const addressDetailRef = useRef<HTMLInputElement>(null);
  const { tenants, addTenant } = useApp();

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [partners, setPartners] = useState<Partner[]>([]);
  const [loadingPartners, setLoadingPartners] = useState(false);

  // 1. 최고 관리자 권한 설정 (상태 & 파트너 배정)
  const [status, setStatus] = useState<'active' | 'pending'>('active');
  const [selectedPartnerId, setSelectedPartnerId] = useState<string>('SYSTEM');
  const [contractRate, setContractRate] = useState<number>(3.0);

  // 2. 단체 기본 정보
  const [religionType, setReligionType] = useState<'buddhist' | 'protestant' | 'catholic' | 'charity' | 'general'>('buddhist');
  const [name, setName] = useState('');
  const [slug, setSlug] = useState('');
  const [slugStatus, setSlugStatus] = useState<{ checked: boolean; isAvailable: boolean; message: string }>({
    checked: false,
    isAvailable: false,
    message: '',
  });

  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);
  const [businessNumber, setBusinessNumber] = useState('');
  const [representative, setRepresentative] = useState('');
  const [address, setAddress] = useState('');
  const [addressDetail, setAddressDetail] = useState('');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  const [description, setDescription] = useState(RELIGION_TYPES[0].defaultDesc);
  const [primaryColor, setPrimaryColor] = useState('#2563EB');

  // 3. 정산 계좌 정보
  const [bankName, setBankName] = useState('국민은행');
  const [accountNumber, setAccountNumber] = useState('');
  const [accountHolder, setAccountHolder] = useState('');

  // 4. 대표 관리자 마스터 계정
  const [adminName, setAdminName] = useState('');
  const [adminEmail, setAdminEmail] = useState('');
  const [adminPhone, setAdminPhone] = useState('');
  const [initialTempPassword, setInitialTempPassword] = useState(() => `fp${Math.floor(100000 + Math.random() * 900000)}`);

  // 파트너 목록 로드
  useEffect(() => {
    setLoadingPartners(true);
    partnerAPI.getAll()
      .then(res => {
        if (res.success && Array.isArray(res.data)) {
          setPartners(res.data);
        }
      })
      .catch(() => {})
      .finally(() => setLoadingPartners(false));
  }, []);

  // 종교 유형 변경 시 기본 설명문 자동 반영 (기존 설명문이 기본값일 때만)
  const handleReligionChange = (newType: typeof religionType) => {
    setReligionType(newType);
    const prevPreset = RELIGION_TYPES.find(r => r.key === religionType);
    const newPreset = RELIGION_TYPES.find(r => r.key === newType);
    if (newPreset && (!description || description === prevPreset?.defaultDesc)) {
      setDescription(newPreset.defaultDesc);
    }
  };

  // 단체명 변경 시 슬러그가 자동 생성 상태이면 영문 자동 추천
  const handleNameChange = (val: string) => {
    setName(val);
    if (!slugStatus.checked && (!slug || isSlugAutoGenerated)) {
      const { converted } = convertKoreanToQwerty(val);
      const clean = (converted || '').toLowerCase().replace(/[^a-z0-9-]/g, '');
      setSlug(clean);
      setIsSlugAutoGenerated(true);
      setSlugStatus({ checked: false, isAvailable: false, message: '' });
    }
  };

  // 슬러그 직접 변경 시 (영문, 숫자, 하이픈 허용 및 한글 2벌식 자동변환)
  const handleSlugChange = (val: string) => {
    setIsSlugAutoGenerated(false);
    const { converted, hasKorean } = convertKoreanToQwerty(val);
    const clean = (converted || '').toLowerCase().replace(/[^a-z0-9-]/g, '');
    setSlug(clean);
    setSlugStatus({ checked: false, isAvailable: false, message: '' });
    if (hasKorean && clean) {
      toast.info(`영문 주소('${clean}')로 자동 변환되었습니다.`, { id: 'slug-convert-toast', duration: 1800 });
    }
  };

  // 슬러그 중복 검사
  const checkSlugAvailability = () => {
    const trimmed = slug.trim().toLowerCase();
    if (!trimmed) {
      toast.error('접속 URL 식별자를 입력해 주세요.');
      return;
    }
    if (trimmed.length < 2) {
      toast.error('식별자는 최소 2글자 이상이어야 합니다.');
      return;
    }

    const isDuplicate = tenants.some(t => t.slug?.toLowerCase() === trimmed);
    if (isDuplicate) {
      setSlugStatus({
        checked: true,
        isAvailable: false,
        message: `'${trimmed}'는 이미 등록된 접속 주소입니다. 다른 주소를 입력해 주세요.`,
      });
      toast.error('이미 사용 중인 주소입니다.');
    } else {
      setSlugStatus({
        checked: true,
        isAvailable: true,
        message: `'soulpay.kr/${trimmed}' 사용 가능합니다.`,
      });
      toast.success('사용 가능한 접속 주소입니다.');
    }
  };

  // 다음 우편번호 검색
  const handleSearchAddress = () => {
    openDaumPostcode((data) => {
      setAddress(data.address);
      setTimeout(() => {
        addressDetailRef.current?.focus();
      }, 100);
    });
  };

  // 폼 제출
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!name.trim()) { toast.error('단체 명칭을 입력해 주세요.'); return; }
    if (!slug.trim()) { toast.error('접속 URL 식별자를 입력해 주세요.'); return; }
    if (!address.trim()) { toast.error('소재지 주소를 입력해 주세요.'); return; }
    if (!phone.trim()) { toast.error('대표 전화번호를 입력해 주세요.'); return; }
    if (!accountNumber.trim()) { toast.error('정산 계좌번호를 입력해 주세요.'); return; }
    if (!adminName.trim()) { toast.error('대표 관리자 성함을 입력해 주세요.'); return; }
    if (!adminEmail.trim()) { toast.error('대표 관리자 로그인 이메일을 입력해 주세요.'); return; }
    if (!adminPhone.trim()) { toast.error('대표 관리자 휴대폰 번호를 입력해 주세요.'); return; }

    const isDup = tenants.some(t => t.slug?.toLowerCase() === slug.trim().toLowerCase());
    if (isDup) {
      toast.error(`'${slug}' 주소는 이미 등록된 중복 주소입니다.`);
      return;
    }

    setIsSubmitting(true);

    const isBuddhist = religionType === 'buddhist';
    const isCatholic = religionType === 'catholic';
    const isCharity  = religionType === 'charity';
    const isGeneral  = religionType === 'general';

    const fullAddress = addressDetail ? `${address.trim()} ${addressDetail.trim()}` : address.trim();

    // 선택된 파트너 정보 매칭
    const assignedPartner = selectedPartnerId !== 'SYSTEM'
      ? partners.find(p => p.id === selectedPartnerId)
      : null;

    const newTenant: Tenant = {
      id: `tenant-${Date.now()}`,
      name: name.trim(),
      slug: slug.trim().toLowerCase(),
      religionType,
      primaryColor,
      address: fullAddress || '소재지 미등록',
      phone: phone.trim() || adminPhone.trim() || '02-0000-0000',
      description: description.trim() || RELIGION_TYPES.find(r => r.key === religionType)?.defaultDesc || '',
      terminology: {
        donation: isBuddhist ? '보시' : isCatholic ? '봉헌' : isCharity ? '후원금' : isGeneral ? '기부금' : '헌금',
        member: isBuddhist ? '불자' : isCatholic ? '교우' : isCharity ? '후원자' : isGeneral ? '기부자' : '성도',
        prayer: isBuddhist ? '축원문' : isCatholic ? '미사지향' : (isCharity || isGeneral) ? '응원 메시지' : '기도문',
      },
      bannerImages: [],
      contact: {
        phone: phone.trim() || adminPhone.trim(),
        email: adminEmail.trim() || email.trim(),
        name: representative.trim() || adminName.trim(),
      },
      adminName: adminName.trim(),
      adminEmail: adminEmail.trim(),
      adminPhone: adminPhone.trim(),
      adminPassword: initialTempPassword,
      contractRate,
      status, // 'active' (즉시 운영 승인) 또는 'pending'
      appliedAt: new Date().toISOString(),
      approvedAt: status === 'active' ? new Date().toISOString() : undefined,
      uniqueNumber: businessNumber.trim() || undefined,
      businessRegistrationNumber: businessNumber.trim() || undefined,
      businessInfo: {
        registrationNumber: businessNumber.trim() || undefined,
        bankName,
        accountNumber: accountNumber.trim(),
        accountHolder: accountHolder.trim() || name.trim(),
        representativeName: representative.trim() || adminName.trim(),
        address: fullAddress,
      },
      paymentConfig: {
        tenantId: `tenant-${Date.now()}`,
        pgProvider: 'tosspayments',
        apiKey: 'test_ck_docs',
        secretKey: 'test_sk_docs',
        mid: 'toss_test_mid',
        devMode: true,
        isActive: status === 'active',
        updatedAt: new Date().toISOString(),
      },
      registrationSource: assignedPartner ? (assignedPartner.role === 'master_agency' ? 'agency' : 'agent') : 'self',
      registeredByPartnerId: assignedPartner?.id,
      registeredByPartnerName: assignedPartner?.name || (selectedPartnerId === 'SYSTEM' ? '플랫폼 본사' : undefined),
      registeredByReferralCode: assignedPartner?.referralCode || (selectedPartnerId === 'SYSTEM' ? 'SYSTEM' : undefined),
      referralCode: assignedPartner?.referralCode || (selectedPartnerId === 'SYSTEM' ? 'SYSTEM' : undefined),
    };

    try {
      await addTenant(newTenant);
      setIsSubmitting(false);
      toast.success(
        `[${name}] 단체가 성공적으로 등록되었습니다. (상태: ${status === 'active' ? '운영중' : '승인대기'})`
      );
      navigate('/system/admin/tenants');
    } catch {
      setIsSubmitting(false);
      toast.error('단체 등록 중 오류가 발생했습니다.');
    }
  };

  return (
    <div className="p-6 sm:p-8 space-y-6 bg-slate-50 min-h-full font-sans w-full">
      {/* 상단 헤더 & 뒤로가기 */}
      <div className="space-y-1">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate('/system/admin/tenants')}
          className="text-slate-500 hover:text-slate-900 -ml-2 h-8 px-2 text-xs font-medium"
        >
          <ArrowLeft className="h-3.5 w-3.5 mr-1.5" /> 단체 목록으로 돌아가기
        </Button>
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-black text-slate-900 tracking-tight">
            신규 단체 개설 및 등록
          </h1>
          <Badge className="bg-blue-600 text-white font-semibold text-xs px-2.5 py-0.5">
            시스템 최고 관리자 전용
          </Badge>
        </div>
        <p className="text-xs text-slate-500 font-medium">
          시스템 관리자 권한으로 가맹단체를 즉시 개설하고, 파트너 배정 및 관리자 마스터 계정을 발급합니다.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">

        {/* ── 1. 최고 관리자 권한 설정 (상태 & 파트너 & 수수료) ── */}
        <Card className="border-slate-200/90 rounded-2xl bg-white shadow-xs">
          <CardHeader className="pb-4 border-b border-slate-100">
            <CardTitle className="text-base font-bold text-slate-900 flex items-center gap-2">
              <ShieldCheck className="h-4 w-4 text-blue-600" /> 운영 권한 및 파트너 배정 설정
            </CardTitle>
            <CardDescription className="text-xs text-slate-500">
              단체 개설 시 초기 운영 상태(즉시 활성화 여부)와 영업 귀속 파트너, 계약 수수료율을 지정합니다.
            </CardDescription>
          </CardHeader>

          <CardContent className="p-6">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
              {/* 운영 상태 */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">
                  초기 운영 상태 *
                </Label>
                <select
                  value={status}
                  onChange={e => setStatus(e.target.value as 'active' | 'pending')}
                  className="w-full h-10 px-3 rounded-lg border border-slate-300 bg-white text-xs font-semibold text-slate-900 focus:outline-none focus:border-blue-500"
                >
                  <option value="active">🟢 즉시 운영 승인 (운영중)</option>
                  <option value="pending">🟡 입점 심사 대기 (승인대기)</option>
                </select>
                <p className="text-[11px] text-slate-500">
                  {status === 'active' ? '개설 즉시 모바일 봉헌 페이지가 활성화됩니다.' : '심사 대기 상태로 등록되며 이후 수동 승인이 필요합니다.'}
                </p>
              </div>

              {/* 영업 파트너 배정 */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">
                  관리 / 영업 귀속 파트너 *
                </Label>
                <select
                  value={selectedPartnerId}
                  onChange={e => setSelectedPartnerId(e.target.value)}
                  className="w-full h-10 px-3 rounded-lg border border-slate-300 bg-white text-xs font-semibold text-slate-900 focus:outline-none focus:border-blue-500"
                >
                  <option value="SYSTEM">🏢 플랫폼 본사 직접 관리 (SYSTEM)</option>
                  {partners.map(p => (
                    <option key={p.id} value={p.id}>
                      {p.role === 'master_agency' ? '🏛️ 대리점' : '👤 영업자'}: {p.name} ({p.referralCode})
                    </option>
                  ))}
                </select>
                <p className="text-[11px] text-slate-500">
                  선택한 파트너의 수수료 원장에 결제 실적이 자동 귀속됩니다.
                </p>
              </div>

              {/* 계약 수수료율 */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">
                  가맹단체 계약 수수료율 (%) *
                </Label>
                <div className="flex items-center gap-2">
                  <Input
                    type="number"
                    step="0.1"
                    min="0.5"
                    max="10.0"
                    value={contractRate}
                    onChange={e => setContractRate(parseFloat(e.target.value) || 0)}
                    className="h-10 text-right font-bold text-slate-900 font-mono text-sm rounded-lg border-slate-300"
                  />
                  <span className="font-bold text-slate-700 text-sm">%</span>
                </div>
                <p className="text-[11px] text-slate-500">
                  플랫폼 표준 권장 수수료율은 3.0%입니다.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* ── 2. 단체 기본 식별 정보 ── */}
        <Card className="border-slate-200/90 rounded-2xl bg-white shadow-xs">
          <CardHeader className="pb-4 border-b border-slate-100">
            <CardTitle className="text-base font-bold text-slate-900 flex items-center gap-2">
              <Building2 className="h-4 w-4 text-blue-600" /> 단체 기본 정보
            </CardTitle>
            <CardDescription className="text-xs text-slate-500">
              종교 유형과 단체 명칭, 고유 접속 URL 주소 및 소재지 정보를 입력합니다.
            </CardDescription>
          </CardHeader>

          <CardContent className="p-6 space-y-5">
            {/* 종교 유형 라디오 버튼 그리드 */}
            <div className="space-y-2">
              <Label className="text-xs font-bold text-slate-800 block">
                종교 및 단체 유형 선택 *
              </Label>
              <div className="grid grid-cols-2 sm:grid-cols-5 gap-2.5">
                {RELIGION_TYPES.map(({ key, label, badge }) => (
                  <button
                    key={key}
                    type="button"
                    onClick={() => handleReligionChange(key as any)}
                    className={`p-3 rounded-xl border text-left transition-all cursor-pointer ${
                      religionType === key
                        ? 'border-blue-600 bg-blue-50/70 text-blue-900 font-bold shadow-2xs'
                        : 'border-slate-200 bg-white text-slate-700 hover:border-slate-300'
                    }`}
                  >
                    <div className="text-[10px] font-semibold text-blue-600 mb-1">{badge}</div>
                    <div className="text-xs">{label}</div>
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
              {/* 단체명 */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">단체 명칭 *</Label>
                <Input
                  placeholder="예: 대한불교 조계종 원광사, 성령교회"
                  value={name}
                  onChange={e => handleNameChange(e.target.value)}
                  className="h-10 text-sm font-semibold rounded-lg border-slate-300"
                  required
                />
              </div>

              {/* 전용 접속 URL Slug */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">접속 URL 식별자 (Slug) *</Label>
                <div className="flex gap-2">
                  <div className="relative flex-1 flex items-center">
                    <span className="absolute left-3 text-xs text-slate-400 font-mono select-none">soulpay.kr/</span>
                    <Input
                      placeholder="wongwangsa"
                      value={slug}
                      onChange={e => handleSlugChange(e.target.value)}
                      className="h-10 pl-24 text-sm font-mono font-bold text-slate-900 rounded-lg border-slate-300"
                      required
                    />
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={checkSlugAvailability}
                    className="h-10 px-3.5 text-xs font-semibold rounded-lg border-slate-300 shrink-0"
                  >
                    중복 확인
                  </Button>
                </div>
                {slugStatus.checked && (
                  <p className={`text-[11px] font-medium ${slugStatus.isAvailable ? 'text-emerald-600' : 'text-rose-600'}`}>
                    {slugStatus.message}
                  </p>
                )}
              </div>

              {/* 사업자등록번호 / 고유번호증 */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">고유번호증 또는 사업자등록번호</Label>
                <Input
                  placeholder="000-00-00000 (선택)"
                  value={businessNumber}
                  onChange={e => setBusinessNumber(e.target.value)}
                  className="h-10 text-sm font-mono rounded-lg border-slate-300"
                />
              </div>

              {/* 대표자 성함 */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">대표자 성함 (주지/담임목사/이사장)</Label>
                <Input
                  placeholder="예: 홍길동 (주지스님)"
                  value={representative}
                  onChange={e => setRepresentative(e.target.value)}
                  className="h-10 text-sm rounded-lg border-slate-300"
                />
              </div>

              {/* 대표 전화번호 */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">공식 대표 전화번호 *</Label>
                <Input
                  placeholder="02-1234-5678 또는 010-0000-0000"
                  value={phone}
                  onChange={e => setPhone(e.target.value)}
                  className="h-10 text-sm rounded-lg border-slate-300"
                  required
                />
              </div>

              {/* 대표 이메일 */}
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">공식 대표 이메일</Label>
                <Input
                  type="email"
                  placeholder="contact@temple.org"
                  value={email}
                  onChange={e => setEmail(e.target.value)}
                  className="h-10 text-sm rounded-lg border-slate-300"
                />
              </div>
            </div>

            {/* 주소 검색 */}
            <div className="space-y-1.5">
              <Label className="text-xs font-bold text-slate-800">단체 소재지 주소 *</Label>
              <div className="flex gap-2">
                <Input
                  readOnly
                  placeholder="주소 검색 버튼을 클릭하세요"
                  value={address}
                  onClick={handleSearchAddress}
                  className="h-10 text-sm bg-slate-50 cursor-pointer rounded-lg border-slate-300"
                  required
                />
                <Button
                  type="button"
                  onClick={handleSearchAddress}
                  className="h-10 px-4 text-xs font-semibold rounded-lg bg-slate-800 text-white hover:bg-slate-900 shrink-0"
                >
                  <Search className="h-3.5 w-3.5 mr-1.5" /> 주소 검색
                </Button>
              </div>
              <Input
                ref={addressDetailRef}
                placeholder="상세 주소를 입력해 주세요 (예: 대웅전 2층 종무소)"
                value={addressDetail}
                onChange={e => setAddressDetail(e.target.value)}
                className="h-10 text-sm rounded-lg border-slate-300 mt-1.5"
              />
            </div>

            {/* 단체 소개글 */}
            <div className="space-y-1.5">
              <Label className="text-xs font-bold text-slate-800">단체 소개글</Label>
              <Textarea
                rows={2}
                value={description}
                onChange={e => setDescription(e.target.value)}
                className="text-xs leading-relaxed rounded-lg border-slate-300 resize-none"
              />
            </div>
          </CardContent>
        </Card>

        {/* ── 3. 정산 계좌 정보 ── */}
        <Card className="border-slate-200/90 rounded-2xl bg-white shadow-xs">
          <CardHeader className="pb-4 border-b border-slate-100">
            <CardTitle className="text-base font-bold text-slate-900 flex items-center gap-2">
              <Building2 className="h-4 w-4 text-blue-600" /> 정산 입금 계좌 정보
            </CardTitle>
            <CardDescription className="text-xs text-slate-500">
              PG사(토스/나노)로부터 결제 대금이 Split 입금될 단체 명의 계좌 정보를 입력합니다.
            </CardDescription>
          </CardHeader>

          <CardContent className="p-6">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">정산 은행 *</Label>
                <select
                  value={bankName}
                  onChange={e => setBankName(e.target.value)}
                  className="w-full h-10 px-3 rounded-lg border border-slate-300 bg-white text-xs font-semibold text-slate-900 focus:outline-none focus:border-blue-500"
                >
                  {BANKS.map(b => (
                    <option key={b} value={b}>{b}</option>
                  ))}
                </select>
              </div>

              <div className="space-y-1.5 sm:col-span-2">
                <Label className="text-xs font-bold text-slate-800">계좌번호 (숫자만 입력) *</Label>
                <Input
                  placeholder="예: 123-456-789012"
                  value={accountNumber}
                  onChange={e => setAccountNumber(e.target.value.replace(/[^0-9-]/g, ''))}
                  className="h-10 text-sm font-mono font-bold text-slate-900 rounded-lg border-slate-300"
                  required
                />
              </div>

              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">예금주명 *</Label>
                <Input
                  placeholder="예: 조계종 원광사 (단체명)"
                  value={accountHolder || name}
                  onChange={e => setAccountHolder(e.target.value)}
                  className="h-10 text-sm font-semibold rounded-lg border-slate-300"
                  required
                />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* ── 4. 대표 관리자 마스터 계정 발급 ── */}
        <Card className="border-slate-200/90 rounded-2xl bg-white shadow-xs">
          <CardHeader className="pb-4 border-b border-slate-100">
            <CardTitle className="text-base font-bold text-slate-900 flex items-center gap-2">
              <UserCheck className="h-4 w-4 text-blue-600" /> 대표 관리자 마스터 계정 발급
            </CardTitle>
            <CardDescription className="text-xs text-slate-500">
              단체 관리자 콘솔(admin.soulpay.kr/{slug || '아이디'})에 로그인할 수 있는 최고 관리자 계정입니다.
            </CardDescription>
          </CardHeader>

          <CardContent className="p-6 space-y-5">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">관리자 성함 *</Label>
                <Input
                  placeholder="예: 김원광 (총무스님)"
                  value={adminName}
                  onChange={e => setAdminName(e.target.value)}
                  className="h-10 text-sm rounded-lg border-slate-300"
                  required
                />
              </div>

              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">로그인 이메일 (아이디) *</Label>
                <Input
                  type="email"
                  placeholder="admin@temple.org"
                  value={adminEmail}
                  onChange={e => setAdminEmail(e.target.value)}
                  className="h-10 text-sm font-medium rounded-lg border-slate-300"
                  required
                />
              </div>

              <div className="space-y-1.5">
                <Label className="text-xs font-bold text-slate-800">관리자 휴대폰 번호 *</Label>
                <Input
                  placeholder="010-1234-5678"
                  value={adminPhone}
                  onChange={e => setAdminPhone(e.target.value)}
                  className="h-10 text-sm rounded-lg border-slate-300"
                  required
                />
              </div>
            </div>

            {/* 초기 임시 비밀번호 */}
            <div className="space-y-1.5 pt-1">
              <Label className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
                <Lock className="h-3.5 w-3.5 text-slate-500" />
                초기 로그인 임시 비밀번호 *
              </Label>
              <div className="flex gap-2 max-w-md">
                <Input
                  value={initialTempPassword}
                  onChange={e => setInitialTempPassword(e.target.value)}
                  className="h-10 font-mono bg-white font-bold text-sm text-slate-900 rounded-lg border-slate-300"
                  required
                />
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setInitialTempPassword(`fp${Math.floor(100000 + Math.random() * 900000)}`)}
                  className="h-10 px-3.5 text-xs font-semibold rounded-lg border-slate-300 bg-white hover:bg-slate-50 shrink-0"
                >
                  <RefreshCw className="h-3.5 w-3.5 mr-1" /> 난수 재발급
                </Button>
              </div>
              <p className="text-[11px] text-slate-500">
                단체 등록 완료 후 대표 관리자에게 이 접속 비밀번호를 전달하여 첫 로그인을 진행할 수 있습니다.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* ── 하단 제출 버튼 ── */}
        <div className="flex items-center justify-end gap-3 pt-2">
          <Button
            type="button"
            variant="outline"
            onClick={() => navigate('/system/admin/tenants')}
            className="h-11 px-5 text-xs font-semibold rounded-xl border-slate-300 text-slate-600"
          >
            취소
          </Button>
          <Button
            type="submit"
            disabled={isSubmitting}
            className="h-11 px-8 text-xs font-bold rounded-xl bg-blue-600 hover:bg-blue-700 text-white shadow-xs cursor-pointer"
          >
            {isSubmitting ? (
              <div className="flex items-center gap-2">
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                <span>단체 등록 처리 중...</span>
              </div>
            ) : (
              '신규 단체 등록 및 개설 완료'
            )}
          </Button>
        </div>

      </form>
    </div>
  );
}
